### ISSUE TITLE
Enhancement: what about making the list draggable

### ISSUE THREAD

**Issue by MiinaMagdy** [efraimnabil/Your-Links-extension#1]
it will be helpful if the list items are draggable, that i want to prioritize some links over another

some thing like this one

![image](https://github.com/efraimnabil/Your-Links-extension/assets/71466151/5571a15e-f693-49f1-9944-53fd59e31817)

**Comment by efraimnabil** [comment]
The feature has been added.

**Comment by MiinaMagdy** [comment]
## there is a bug
when I `save tap` and try to drag them it does nothing.

**Comment by efraimnabil** [comment]
Ok, I will solve it, ISA.

**Done**, The Bug has been Solved

**Comment by MiinaMagdy** [comment]
> Ok, I will solve it, ISA.
> 
> **Done**, The Bug has been Solved

Thanks @efraimnabil for responding, this is extremely helpful.
